name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.3
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  chopper: ^4.0.1
  json_annotation: ^4.4.0
  http: ^0.13.4
  swipable_stack: ^1.2.0
  cached_network_image: ^3.2.0
  google_fonts: ^2.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

<<<<<<< HEAD
  flutter_gen: ^4.1.6
=======

  # flutter_gen: ^4.1.6
>>>>>>> 27fe72958701c08a555ae80cb3cccbcc0ec5d6c2
  freezed: ^1.1.1
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0



<<<<<<< HEAD
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
=======
# flutter_gen:
#   output: lib/gen/ # Optional (default: lib/gen/)
#   line_length: 80 # Optional (default: 80)
>>>>>>> 27fe72958701c08a555ae80cb3cccbcc0ec5d6c2

flutter:
  uses-material-design: true
  assets:
    - assets/actual/
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
